вывел список ингредиентов
htmlacademy-vue/1562731-pizza-1 pull request #1
Opened 2022-03-28 20:52 UTC by Lagutin-Ruslan

2022-03-29 02:16 UTC, enotke requested changes

2022-03-29 02:16 UTC, enotke commented on src/frontend/src/views/Index.vue
> +                <h2 class="title title--small sheet__title">Выберите тесто</h2>
Тип теста и размер пиццы тоже нужно импортировать из статических json-файлов

2022-03-29 02:16 UTC, enotke commented on src/frontend/src/views/Index.vue
> +                <h2 class="title title--small sheet__title">Выберите тесто</h2>
И соус тоже

2022-04-05 13:09 UTC, Lagutin-Ruslan commented on src/frontend/src/views/Index.vue
> +                <h2 class="title title--small sheet__title">Выберите тесто</h2>
Вывел остальные данные. Закоммитил, запушил.

2022-04-07 22:09 UTC, enotke requested changes

2022-04-07 22:09 UTC, enotke commented on src/frontend/src/views/Index.vue
> +    <body>
Теги html, head и body тут не нужны. Они генерируются сборщиком.

2022-04-07 22:09 UTC, enotke commented on src/frontend/src/views/Index.vue
> +                    class="diameter__input diameter__input--big"
класс diameter__input--big должен меняться в зависимости от размера

2022-04-07 22:09 UTC, enotke commented on src/frontend/src/views/Index.vue
> +                    class="dough__input dough__input--light"
класс dough__input--light должен меняться в зависимости от типа теста

2022-04-07 22:09 UTC, enotke commented on src/frontend/src/views/Index.vue
> +                        v-for="ingredient of Pizza.ingredients"
Тут тоже. Каждому ингредиенту соответствует модификатор. Например filling--mushrooms

2022-04-21 03:49 UTC, merged